version: '3'
services:
  cartracking:
    image: __CI_APPLICATION_REPOSITORY__:__VERSION__
    environment:
      - VIRTUAL_HOST=__VIRTUAL_HOST__
      - VIRTUAL_PORT=__VIRTUAL_PORT__
      - LETSENCRYPT_HOST=__VIRTUAL_HOST_SSL__
      - MAXLOCATION=__MAXLOCATION__
      - SECRET=__SECRET__

  cartracking-api:
    image: __CI_APPLICATION_REPOSITORY__:__VERSION__
    environment:
      - VIRTUAL_HOST=api.__VIRTUAL_HOST__
      - VIRTUAL_PORT=__VIRTUAL_PORT__
      - MAXLOCATION=__MAXLOCATION__
      - SECRET=__SECRET__
      - API=true

  mongo:
    image: mongo
    volumes:
    - cartracking-data:/data/db

volumes:
  cartracking-data: