version: '3'
services:
  cartracking:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MAXLOCATION=30
      - SECRET=NOTASECRET

  cartracking-api:
    build: .
    ports:
      - "3001:3000"
    environment:
      - MAXLOCATION=30
      - SECRET=NOTASECRET
      - API=true

  mongo:
    image: mongo
    volumes:
    - cartracking-data:/data/db

volumes:
  cartracking-data: